name: Train Model in Development and Production

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  train-dev:
    name: Train Model in Development
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3  # Check out the repository code

    - name: Install Azure ML CLI extension
      run: az extension add -n ml -y  # Install Azure ML CLI extension

    - name: Azure login
      uses: azure/login@v1  # Log into Azure using service principal credentials
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Submit Dev Job
      run: |
        az ml job create --file src/job-dev.yml \
          --resource-group mldemo \
          --workspace-name mldemows \
          --stream

  train-prod:
    name: Train Model in Production
    runs-on: ubuntu-latest
    needs: train-dev  # Ensure dev job succeeds first
    steps:
    - name: Check out repo
      uses: actions/checkout@v3  # Check out the repository code

    - name: Install Azure ML CLI extension
      run: az extension add -n ml -y  # Install Azure ML CLI extension

    - name: Azure login
      uses: azure/login@v1  # Log into Azure using service principal credentials
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Submit Prod Job
      run: |
        az ml job create --file src/job-prod.yml \
          --resource-group mldemo \
          --workspace-name mldemows \
          --stream